### PR TITLE
Personal Portfolio Phase 3 v1

### PR DESCRIPTION
**Pull request by andrewmdav**
A hangup that I couldn't fix was the size of the first picture link in my portfolio library.  My goal was to make them width/height 200 in the html,  For some reason, the first picture keeps coming up short.  Any suggestions would be appreciated, as I was hoping it would look a little more professional than it does currently.

### CODE REVIEW

**Comment by mbMosman** [comment]
I don't actually have time right now to look at this, probably not until Wed as I am in class all day tomorrow.  However, if you have not already done this, it helps to size the images consistently in the actual image files before trying to fit them on the web.  If you have images of different sizes, that can make the display more difficult, and sometimes distort the images as they are sized to fit.

**Comment by andrewmdav** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } No worries- this advice really helped.  I did not know how to do this before now.  It appears good enough for me at this point.  I will finish the resubmission screen shots in the morning.  Thank you!!


Sent from Yahoo Mail for iPhone


On Monday, May 1, 2017, 3:11 PM, Mary Mosman <notifications@github.com> wrote:


I don't actually have time right now to look at this, probably not until Wed as I am in class all day tomorrow. However, if you have not already done this, it helps to size the images consistently in the actual image files before trying to fit them on the web. If you have images of different sizes, that can make the display more difficult, and sometimes distort the images as they are sized to fit.

**Comment by andrewmdav** [comment]
Thank you for the gallery comment.  I took your advice, and it appears to work!

**Comment by mbMosman** [comment]
Nice work!  Finished project looks great.

**Pull request closed without merging**
